version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies (if any)..."
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Hello from CodeBuild!"
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
