version: 0.2

phases:
  install:
    # runtime-versions:
    #   python: 3.12
    commands:
      - echo "Installing OS dependencies..."
      - yum install -y make zip unzip wget || true
      - echo "Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.13.2/terraform_1.13.2_linux_amd64.zip
      - unzip terraform_1.13.2_linux_amd64.zip -d /usr/local/bin/
      - terraform -version
      - python3 --version
      - echo "Installing Python dependencies..."
      - pip3 install --upgrade pip
      - pip3 install -r requirements.txt  
  pre_build:
    commands: 
      - echo "Running Python unit tests..."
      - pytest tests/ --junitxml=test-results/results.xml

  build:
    commands:
      - echo "Running Terraform validation..."
      - terraform init -input=false -upgrade
      - terraform fmt -recursive
      - terraform fmt -check
      - terraform validate

  post_build:
    commands:
      - echo "Deploying with Terraform..."
      - terraform plan
      - terraform apply -auto-approve -input=false
      - echo "Build and deployment completed on `date`"
      - python3 --version

artifacts:
  files:
    - '**/*'
  discard-paths: no
  exclude-files:
    - '.terraform/**'
